name: 'RPM Build'
description: 'Build RPMs from spec file and upload it as Artifact or Release Asset'
author: 'Grigory Efimov'

inputs:
  platform:
    description: 'Build target architecture (e.g., linux/amd64, linux/arm64)'
    required: false
    default: 'linux/amd64'
  docker-image:
    description: 'Docker image (e.g amazonlinux:2, ubuntu:latest)'
    required: false
    default: 'amazonlinux:2'
  pre-build-command:
    description: 'Pre build command (e.g yum install -y rpmdevtools'
    required: false
    default: 'yum install -y rpm-build rpmdevtools gcc make coreutils python git rsync yum-utils GeoIP-devel'

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.platform }}

    - name: build on ${{ inputs.docker-image }} platform=${{ inputs.platform }}
      shell: bash
      run: |
        docker run \
          --platform ${{ inputs.platform }} \
          --rm \
          --volume ${{ github.workspace }}:/workspace \
          --volume ${{ github.action_path }}:/action_path \
          --workdir /workspace \
          amazonlinux:2 \
          /bin/bash -c \
            "uname -a
            ${{ inputs.pre-build-command }}
            /action_path/build.sh
            "

branding:
  icon: 'package'
  color: 'red'
