on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

name: release

jobs:
  release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
